clc;
clear;

Ha_Fe_Feature = cell(1,21);

Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\02\ha_fe.mat');
Ha_Fe_Feature{1,1} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\03\ha_fe.mat');
Ha_Fe_Feature{1,2} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\04\ha_fe.mat');
Ha_Fe_Feature{1,3} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\06\ha_fe.mat');
Ha_Fe_Feature{1,4} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\07\ha_fe.mat');
Ha_Fe_Feature{1,5} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\08\ha_fe.mat');
Ha_Fe_Feature{1,6} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\09\ha_fe.mat');
Ha_Fe_Feature{1,7} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\10\ha_fe.mat');
Ha_Fe_Feature{1,8} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\11\ha_fe.mat');
Ha_Fe_Feature{1,9} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\12\ha_fe.mat');
Ha_Fe_Feature{1,10} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\13\ha_fe.mat');
Ha_Fe_Feature{1,11} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\14\ha_fe.mat');
Ha_Fe_Feature{1,12} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\15\ha_fe.mat');
Ha_Fe_Feature{1,13} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\16\ha_fe.mat');
Ha_Fe_Feature{1,14} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\17\ha_fe.mat');
Ha_Fe_Feature{1,15} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\18\ha_fe.mat');
Ha_Fe_Feature{1,16} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\19\ha_fe.mat');
Ha_Fe_Feature{1,17} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\20\ha_fe.mat');
Ha_Fe_Feature{1,18} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\21\ha_fe.mat');
Ha_Fe_Feature{1,19} = Feature.Histogram;
%Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\22\di_su.mat');
%Fe_Fe_Feature{1,20} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\23\ha_fe.mat');
Ha_Fe_Feature{1,20} = Feature.Histogram;
Feature = load('F:\Codes\LBP-TOP\LBP_TOP_4Frames_Feature\24\ha_fe.mat');
Ha_Fe_Feature{1,21} = Feature.Histogram;

save('F:\Codes\LBP-TOP\4Frames_Features\Fe\Ha_Fe_Feature.mat','Ha_Fe_Feature');
